### PR TITLE
Add some SDL2 extension libraries

### PR DESCRIPTION
**Pull request by Andre-LA**
Libraries included in this PR:

* [SDL_image](https://www.libsdl.org/projects/SDL_image/)
* [SDL_ttf](https://www.libsdl.org/projects/SDL_ttf/)
* [SDL_mixer](https://www.libsdl.org/projects/SDL_mixer/)

A test file was also added.
Since these libraries are _"extension libraries"_, I decided to keep them separated from `sdl2` as `sdl2-extras` on the Makefile.

### CODE REVIEW

**Comment by edubart** [comment]
Thanks for adding these libraries! I've tested now, the `on-off.png` image is missing when running the tests.

**Comment by Andre-LA** [comment]
Oh, I didn't noticed.

Looked now, there is a `*.png` on the `.gitignore` file, should I remove it?

**Comment by edubart** [comment]
Yea you can remove, so the test pass.

**Comment by Andre-LA** [comment]
removed and png file added.

**Comment by edubart** [comment]
Thanks, merged! I've added some extra changes to the test file, so I can use it when testing all bindings with `make test-all-extra` here.

**Pull request merged**
